version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: thevace_frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
