version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    networks:
      - vace-network

networks:
  vace-network:
    external: true
