version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
      JWT_SECRET: ${JWT_SECRET:-your_secure_jwt_secret}
    networks:
      - vace-network
    ports:
      - "3000:3000"
    # Host makinedeki PostgreSQL'e erişim için (gerekirse)
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  vace-network:
    external: true
